default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

# development:
#   <<: *default
#   database: db/development.sqlite3

development:
  adapter: mysql2
  encoding: utf8
  database: db_fertilization_mp
  username: root
  password: password
  host: 127.0.0.1
  port: 3306

test:
  <<: *default
  database: db/test.sqlite3

production:
  adapter: postgresql
  database: d68e3n2f8k0j85
  username: nkzwtwoeygprwm
  password: 8cb093db5b90caa8b2518af1d331d727623b590dbc17427c71526d3997a43b48
  pool: 5
  timeout: 5000
