default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  adapter: postgresql
  database: d68e3n2f8k0j85
  username: nkzwtwoeygprwm
  password: 8cb093db5b90caa8b2518af1d331d727623b590dbc17427c71526d3997a43b48
  pool: 5
  timeout: 5000

# development: &development
#   adapter: postgresql
#   encoding: utf8
#   database: db_fertilization_mp
#   username: postgres
#   password: password
#   pool: 5 # not mandatory
#   timeout: 5000 # not mandatory
#   host: localhost
#   port: 5432 # your postgresql port number (5432 or 5433)
#
# test:
#   adapter: postgresql
#   encoding: utf8
#   database: db_fertilization_mp
#   username: postgres
#   password: password
#   pool: 5 # not mandatory
#   timeout: 5000 # not mandatory
#   host: localhost
#   port: 5432 # your postgresql port number (5432 or 5433)
#
# production:
#   adapter: postgresql
#   database: ENTER_LATER
#   username: ENTER_LATER
#   password: ENTER_LATER
#   pool: 5
#   timeout: 5000
